# docker-compose.yml
version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:v1.8.1
    container_name: qdrant
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # gRPC (optional)
    volumes:
      - ./database:/qdrant/storage
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./images:/app/images
    depends_on:
      - qdrant
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
